version: "3.9"
services:
  sftphost:
    image: atmoz/sftp:alpine
    volumes:
      - ./.ssh/id_ecdsa.pub:/home/ecdsa_user/.ssh/keys/id_ecdsa.pub:ro
      - ./.ssh/id_ed25519.pub:/home/ed25519_user/.ssh/keys/id_ed25519.pub:ro
      - ./.ssh/id_rsa.pub:/home/rsa_user/.ssh/keys/id_rsa.pub:ro
      - ./host/users.conf:/etc/sftp/users.conf:ro
      - ./host/download:/home/ecdsa_user/download
      - ./host/download:/home/ed25519_user/download
      - ./host/download:/home/rsa_user/download
      - ./host/upload:/home/ecdsa_user/upload
      - ./host/upload:/home/ed25519_user/upload
      - ./host/upload:/home/rsa_user/upload

  install:
    image: node:alpine
    volumes:
      - ./client:/opt/code
    working_dir: /opt/code
    command: sh -c "npm install"

  build:
    image: node:alpine
    volumes:
      - ./client:/opt/code
    working_dir: /opt/code
    command: sh -c "npm run build"

  lint:
    image: node:alpine
    volumes:
      - ./client:/opt/code
    working_dir: /opt/code
    command: sh -c "npm run lint"

  test:
    image: node:alpine
    volumes:
      - ./client:/opt/code
      - ./.ssh:/opt/.ssh
      - ./.gnupg:/opt/.gnupg
      - ./host:/tmp/host
    environment:
      - SFTP_HOST_NAME=sftphost
      - HOST_VOLUME=/tmp/host
      - AWS_DEFAULT_REGION=ap-southeast-2
    depends_on:
      - sftphost
    links:
      - sftphost
    working_dir: /opt/code
    command: sh -c "bin/wait-for sftphost:22 -t 5 -- npm test"
